version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8085:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
    ports:
      - "3307:3306"

  kong:
    image: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    ports:
      - "8001:8000"
    volumes:
      - ./api/kong.yml:/etc/kong/kong.yml
