version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root  # Root password for MySQL
    volumes:
      - db_data:/var/lib/mysql  # Persistent storage for MySQL data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization script
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

volumes:
  db_data:
