version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
