version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8086:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
    ports:
      - "3308:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  kong:
    image: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
    ports:
      - "8005:8000"
    volumes:
      - ./api/kong.yml:/etc/kong/kong.yml
