services:
  frontend:
    build: frontend:latest
    ports:
      - "8085:80"
    container_name: "frontend"

  backend:
    build: backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - database
      - frontend
    container_name: "backend"

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employees
    container_name: "db"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
