pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/yourusername/EMS_Project.git'
            }
        }
        stage('Build') {
            steps {
                sh 'docker-compose up --build -d'
            }
        }
        stage('Test') {
            steps {
                sh 'curl -X GET http://localhost:5000/employees'
            }
        }
    }
}
