services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: <DB_Private_IP>
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: employees
    container_name: be-container
    restart: unless-stopped
